TaskProgressBar documented with Storybook
dani17b/lib-productivio pull request #12
Opened 2023-03-15 16:59 UTC by irismck

It throws this error (but works): 
![image](https://user-images.githubusercontent.com/127731483/225384483-a990901d-dcb8-4e04-b184-4755e86c0bc5.png)

2023-03-16 16:50 UTC, thepaulaseoane requested changes

2023-03-16 16:50 UTC, thepaulaseoane commented on src/components/taskProgressBar/TaskProgressBar.tsx
> +  text?: string;
Estaría bien que este nombre fuese más específico, así como la descripción, para saber de forma más concreta qué tipo de texto introducir.

2023-03-17 07:41 UTC, IvanL9 commented on src/components/taskProgressBar/TaskProgressBar.stories.mdx
> +        percentage : 0
Se podria añadir un limite para que la gente no pueda poner mas de 100%

2023-03-17 08:46 UTC, IvanL9 approved these changes

2023-03-17 08:48 UTC, thepaulaseoane approved these changes

2023-03-17 08:48 UTC, merged