Added rollup config to generate dists
dani17b/lib-productivio pull request #22
Opened 2023-03-16 13:03 UTC by dani17b

2023-03-16 16:26 UTC, XavierNovoa requested changes

2023-03-16 16:26 UTC, XavierNovoa commented on package.json
> +    "sass": "^1.59.3",
circunflejo

2023-03-16 16:40 UTC, thepaulaseoane requested changes

2023-03-16 16:40 UTC, thepaulaseoane commented on package.json
> +    "@rollup/plugin-commonjs": "^24.0.1",
Más circunflejos

2023-03-16 16:41 UTC, FerV02 requested changes

2023-03-16 16:41 UTC, FerV02 commented on tsconfig.json
> +    "emitDeclarationOnly": true,
Sobra la coma de  "emitDeclarationOnly"

2023-03-17 07:42 UTC, thepaulaseoane approved these changes

2023-03-17 07:43 UTC, XavierNovoa approved these changes

2023-03-17 07:46 UTC, FerV02 approved these changes

2023-03-17 07:46 UTC, IsFriskis commented on package.json
> +    "@storybook/testing-library": "0.0.13",
Todas las dependencias de @, son partes de la libreria. En caso de que se quiera la libreria entera y para mayor comodidad, recomendaria un "yarn add storybook" o "npm i storybook"

2023-03-17 08:36 UTC, merged