TimeComponent for the feed first version
dani17b/lib-productivio pull request #57
Opened 2023-03-21 16:09 UTC by ariashector19

result:
![image](https://user-images.githubusercontent.com/127731487/226669724-9695e7b1-b4b2-456f-a36b-1eca7c533d65.png)

2023-03-21 16:48 UTC, thepaulaseoane requested changes
Puedes exportar el componente en index.ts para que ya esté listo para utilizar en la web sin necesidad de hacer ese paso a mayores más tarde

2023-03-21 16:48 UTC, thepaulaseoane commented on src/components/timeAgo/Timeago.stories.mdx
> +TimeAgo component.
Deberías explicar mejor lo que hace el componente y cómo funciona, especificando cómo introducir las fechas para que no salten errores

2023-03-21 16:54 UTC, Br1lopez requested changes
Different texts

2023-03-21 16:54 UTC, Br1lopez commented on src/components/timeAgo/TimeAgo.tsx
> +  return <span className="time">{timeAgo}</span>;
Aquí pondria un replace que eliminase "alrededor de". 

Mejor que ponga "hace 2 horas" y ya.

2023-03-21 16:56 UTC, ariashector19 commented on src/components/timeAgo/TimeAgo.tsx
> +  return <span className="time">{timeAgo}</span>;
perfe

2023-03-22 09:53 UTC, Br1lopez approved these changes
Todo perfecto

2023-03-22 15:16 UTC, thepaulaseoane approved these changes

2023-03-22 16:58 UTC, merged