TaskProgressBars, default colors with null
dani17b/lib-productivio pull request #89
Opened 2023-03-23 16:49 UTC by IsFriskis

2023-03-23 16:56 UTC, irismck approved these changes

2023-03-24 12:02 UTC, XavierNovoa requested changes

2023-03-24 12:02 UTC, XavierNovoa commented on src/components/taskProgressBar/TaskProgressBar.tsx
>      backgroundColor: parentBackgroundColor,
No hace falta comprobar que sea null, puedes hacer:
```ts
backgroundColor: parentBackgroundColor || DefaultParentColor
```

Lo mismo para el child

2023-03-28 09:58 UTC, XavierNovoa approved these changes

2023-03-28 15:13 UTC, merged